"""followers

Revision ID: 287d40be25f1
Revises: e44bea8a8001
Create Date: 2021-02-19 11:56:23.600599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287d40be25f1'
down_revision = 'e44bea8a8001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
