version: '3.3'
services:
  realest-estate-tests:
    build:
      context: ./
      dockerfile: Dockerfile
    command: wait-for-it realest-estate-db:5435 -- python manage.py test --noinput
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=realest_estate
      - DB_HOST=realest-estate-db
      - DB_PORT=5435
    depends_on:
      - realest-estate-db
  realest-estate-web:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DEV_MODE: 'true'
      DB_HOST: realest-estate-db
    command: wait-for-it realest-estate-db:5435 -- bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - realest-estate-db
  realest-estate-db:
    image: postgres:12
    container_name: realest-estate-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=realest_estate
    volumes:
      - ./.docker/data/realest-db:/var/lib/postgresql/data
volumes:
  realest-db:
