"""modify tenant model

Revision ID: ee017c20978a
Revises: 3acc352b9fea
Create Date: 2025-05-07 08:09:04.296648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee017c20978a'
down_revision: Union[str, None] = '3acc352b9fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'db_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenants', 'db_user',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenants', 'db_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenants', 'db_host',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenants', 'db_port',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'db_port',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tenants', 'db_host',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tenants', 'db_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tenants', 'db_user',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tenants', 'db_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
